version: "3"

services:

  app:
    image: fcgi_c:v1.4
    build:
      context: .
      dockerfile: Dockerfile

  server:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./part6/nginx.conf:/etc/nginx/nginx.conf